[versions]
apiVersion = "1.8"
binaryValidator = "0.15.0-Beta.2"
dokka = "1.9.20"
javaVersion = "8"
junit5-jupiter = "5.10.2"
kotlin = "2.0.0-RC3"
kotlinx-serialization = "1.7.0-RC"
kxml2 = "2.3.0"
woodstox = "6.6.2"
xmlutil = "0.90.0-SNAPSHOT"

[libraries]
woodstox = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstox" }
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }

junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5-jupiter" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5-jupiter" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin"}

[plugins]
binaryValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryValidator" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
