[versions]
junit5-jupiter = "5.10.1"
kotlinx-serialization = "1.6.2"
kotlin = "1.9.23"
dokka = "1.9.10"
binaryValidator = "0.14.0"
woodstox = "6.5.1"
javaVersion = "8"
apiVersion = "1.8"
xmlutil = "0.90.0-SNAPSHOT"

[libraries]
logback-classic = "ch.qos.logback:logback-classic:1.4.7"
woodstox = { module = "com.fasterxml.woodstox:woodstox-core", version.ref="woodstox" }
kxml2 = "net.sf.kxml:kxml2:2.3.0"

junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5-jupiter" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5-jupiter" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin"}

[plugins]
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref="kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref="kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref="kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref="kotlin" }
kotlinJs = { id = "org.jetbrains.kotlin.js", version.ref="kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref="dokka" }
binaryValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref="binaryValidator" }
